fint:
  adapter:
    id: https://vigoiks.no/fintlabs-no/personvern/samtykke-henrik
    password:
    username:
    base-url: http://localhost:8081
#    base-url: https://alpha.felleskomponent.no
    registration-id: fint
    org-id: fintlabs.no
    heartbeat-interval: 1
    capabilities:
      otungdom:
        domain-name: utdanning
        packageName: ot
        resource-name: otungdom
        fullSyncIntervalInDays: 1
        deltaSyncInterval: IMMEDIATE

spring:
  security:
    oauth2:
      client:
        provider:
          fint-idp:
            token-uri: https://idp.felleskomponent.no/nidp/oauth/nam/token?resourceServer
        registration:
          fint:
            authorization-grant-type: password
            client-id:
            client-secret:
            provider: fint-idp
            scope: fint-adapter openid

  datasource:
    hikari:
      schema: public
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5436/fint_utdanning_ot_adapter
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    datasource:
      driver-class-name: org.postgresql.Driver
    flyway:
      locations: classpath:db/migration
