apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mrfylke-no
resources:
  - ../../../base
commonLabels:
  app.kubernetes.io/name: fint-utdanning-ot-adapter
  app.kubernetes.io/instance: fint-utdanning-ot-adapter_mrfylke_no
  app.kubernetes.io/version: latest
  app.kubernetes.io/component: adapter
  app.kubernetes.io/part-of: fint-core
  fintlabs.no/team: core
  fintlabs.no/org-id: mrfylke.no

patches:
  - patch: |-
      - op: replace
        path: "/metadata/labels/app.kubernetes.io~1instance"
        value: "fint-utdanning-ot-adapter_mrfylke_no"
      - op: replace
        path: "/spec/orgId"
        value: "mrfylke.no"
      - op: replace
        path: "/spec/env/1/value"
        value: "15"
      - op: replace
        path: "/spec/env/2/value"
        value: "https://beta.felleskomponent.no"
      - op: replace
        path: "/spec/env/3/value"
        value: "mrfylke.no"
    target:
      kind: Application
      name: fint-utdanning-ot-adapter

  - patch: |-
      - op: replace
        path: "/metadata/labels/app.kubernetes.io~1instance"
        value: "fint-utdanning-ot-adapter_mrfylke_no"
      - op: replace
        path: "/spec/orgId"
        value: "mrfylke.no"
    target:
      kind: FintAdapter
      name: utdanning-ot-adapter