apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tffk-no
resources:
  - ../../../base
commonLabels:
  app.kubernetes.io/name: fint-utdanning-ot-adapter
  app.kubernetes.io/instance: fint-utdanning-ot-adapter_tffk_no
  app.kubernetes.io/version: latest
  app.kubernetes.io/component: adapter
  app.kubernetes.io/part-of: fint-core
  fintlabs.no/team: core
  fintlabs.no/org-id: tffk.no

patches:
  - patch: |-
      - op: replace
        path: "/metadata/labels/app.kubernetes.io~1instance"
        value: "fint-utdanning-ot-adapter_tffk_no"
      - op: replace
        path: "/spec/orgId"
        value: "tffk.no"
      - op: replace
        path: "/spec/env/1/value"
        value: "54"
      - op: replace
        path: "/spec/env/2/value"
        value: "https://api.felleskomponent.no"
      - op: replace
        path: "/spec/env/3/value"
        value: "tffk.no"
      - op: replace
        path: "/spec/env/4/value"
        value: https://vigoiks.no/tffk-no/utdanning/ot
      - op: replace
        path: "/spec/onePassword/itemPath"
        value: "vaults/aks-api-vault/items/fint-utdanning-ot-adapter"
    target:
      kind: Application
      name: fint-utdanning-ot-adapter

  - patch: |-
      - op: replace
        path: "/metadata/labels/app.kubernetes.io~1instance"
        value: "fint-utdanning-ot-adapter_tffk_no"
      - op: replace
        path: "/spec/orgId"
        value: "tffk.no"
    target:
      kind: FintAdapter
      name: utdanning-ot-adapter